config/routes.rb
Rails.application.routes.draw do
  root 'degree_plans#index'

  resources :courses
  resources :term_items
  resources :course_term_items
  resources :term_item_terms
  resources :terms
  resources :users
  resources :degree_plans do
    member do
      get 'csv'
    end
  end
  resources :departments
  resources :colleges
  resources :years

end

app/models/college.rb
class College < ActiveRecord::Base
  belongs_to :year
  has_many :departments
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
end

app/models/course_term_item.rb
class CourseTermItem < ActiveRecord::Base
  belongs_to :course
  belongs_to :term_item
end

app/models/degree_plan.rb
class DegreePlan < ActiveRecord::Base
  belongs_to :department
  has_many :terms
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :college
  has_many :degree_plans
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :degree_plan
  has_many :term_items
end

app/models/term_item.rb
class TermItem < ActiveRecord::Base
  belongs_to :term
  has_many :course_term_items
  has_many :courses, through: :course_term_items
end

app/models/term_item_term.rb
class TermItemTerm < ActiveRecord::Base
  belongs_to :term
  belongs_to :term_item
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :department
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :colleges
end

app/controllers/term_item_terms_controller.rb
class TermItemTermsController < ApplicationController
  before_action :set_term_item_term, only: [:show, :edit, :update, :destroy]

  # GET /term_item_terms
  # GET /term_item_terms.json
  def index
    @term_item_terms = TermItemTerm.all
  end

  # GET /term_item_terms/1
  # GET /term_item_terms/1.json
  def show
  end

  # GET /term_item_terms/new
  def new
    @term_item_term = TermItemTerm.new
  end

  # GET /term_item_terms/1/edit
  def edit
  end

  # POST /term_item_terms
  # POST /term_item_terms.json
  def create
    @term_item_term = TermItemTerm.new(term_item_term_params)

    respond_to do |format|
      if @term_item_term.save
        format.html { redirect_to @term_item_term, notice: 'Term item term was successfully created.' }
        format.json { render :show, status: :created, location: @term_item_term }
      else
        format.html { render :new }
        format.json { render json: @term_item_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /term_item_terms/1
  # PATCH/PUT /term_item_terms/1.json
  def update
    respond_to do |format|
      if @term_item_term.update(term_item_term_params)
        format.html { redirect_to @term_item_term, notice: 'Term item term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term_item_term }
      else
        format.html { render :edit }
        format.json { render json: @term_item_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /term_item_terms/1
  # DELETE /term_item_terms/1.json
  def destroy
    @term_item_term.destroy
    respond_to do |format|
      format.html { redirect_to term_item_terms_url, notice: 'Term item term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term_item_term
      @term_item_term = TermItemTerm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_item_term_params
      params.require(:term_item_term).permit(:term_id, :term_item_id)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)
    @term.number = @term.degree_plan.terms.size + 1

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
        format.js
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:degree_plan_id)#, :number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:department_id, :netid, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/degree_plans_helper.rb
module DegreePlansHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/term_item_terms_helper.rb
module TermItemTermsHelper
end

app/helpers/term_items_helper.rb
module TermItemsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/term_item_terms/_form.html.erb
<%= form_for(@term_item_term) do |f| %>
  <% if @term_item_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term_item_term.errors.count, "error") %> prohibited this term_item_term from being saved:</h2>

      <ul>
      <% @term_item_term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term_id %><br>
    <%= f.text_field :term_id %>
  </div>
  <div class="field">
    <%= f.label :term_item_id %><br>
    <%= f.text_field :term_item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/term_item_terms/edit.html.erb
<h1>Editing Term Item Term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term_item_term %> |
<%= link_to 'Back', term_item_terms_path %>

app/views/term_item_terms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Term Item Terms</h1>

<table>
  <thead>
    <tr>
      <th>Term</th>
      <th>Term item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @term_item_terms.each do |term_item_term| %>
      <tr>
        <td><%= term_item_term.term %></td>
        <td><%= term_item_term.term_item %></td>
        <td><%= link_to 'Show', term_item_term %></td>
        <td><%= link_to 'Edit', edit_term_item_term_path(term_item_term) %></td>
        <td><%= link_to 'Destroy', term_item_term, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term item term', new_term_item_term_path %>

app/views/term_item_terms/new.html.erb
<h1>New Term Item Term</h1>

<%= render 'form' %>

<%= link_to 'Back', term_item_terms_path %>

app/views/term_item_terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @term_item_term.term %>
</p>

<p>
  <strong>Term item:</strong>
  <%= @term_item_term.term_item %>
</p>

<%= link_to 'Edit', edit_term_item_term_path(@term_item_term) %> |
<%= link_to 'Back', term_item_terms_path %>