config/routes.rb
Rails.application.routes.draw do
  root 'degree_plans#index'

  resources :courses
  resources :term_items
  resources :course_term_items
  resources :term_item_terms
  resources :terms
  resources :users
  resources :degree_plans do
    member do
      get 'csv'
    end
  end
  resources :departments
  resources :colleges
  resources :years

end

app/models/degree_plan.rb
class DegreePlan < ActiveRecord::Base
  belongs_to :department
  has_many :terms
end

app/controllers/degree_plans_controller.rb
require 'csv'

class DegreePlansController < ApplicationController
  before_action :set_degree_plan, only: [:show, :edit, :update, :destroy, :csv]

  # GET /degree_plans
  # GET /degree_plans.json
  def index
    @degree_plans = DegreePlan.all
  end

  # GET /degree_plans/1
  # GET /degree_plans/1.json
  def show
  end

  # GET /degree_plans/new
  def new
    @degree_plan = DegreePlan.new
  end

  # GET /degree_plans/1/edit
  def edit
  end

  # POST /degree_plans
  # POST /degree_plans.json
  def create
    @degree_plan = DegreePlan.new(degree_plan_params)

    respond_to do |format|
      if @degree_plan.save
        format.html { redirect_to @degree_plan, notice: 'Degree plan was successfully created.' }
        format.json { render :show, status: :created, location: @degree_plan }
      else
        format.html { render :new }
        format.json { render json: @degree_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degree_plans/1
  # PATCH/PUT /degree_plans/1.json
  def update
    respond_to do |format|
      if @degree_plan.update(degree_plan_params)
        format.html { redirect_to @degree_plan, notice: 'Degree plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree_plan }
      else
        format.html { render :edit }
        format.json { render json: @degree_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degree_plans/1
  # DELETE /degree_plans/1.json
  def destroy
    @degree_plan.destroy
    respond_to do |format|
      format.html { redirect_to degree_plans_url, notice: 'Degree plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def csv
    @csv = CSV.generate do |csv|
      csv << ["Term","Description","Hours","Minimum Grade","Notes"]
      @degree_plan.terms.flat_map(&:term_items).each do |item|
        csv << [item.term.number, item.description, item.hours, item.minimum_grade, item.notes]
      end
    end

    respond_to do |format|
      format.csv
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree_plan
      @degree_plan = DegreePlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_plan_params
      params.require(:degree_plan).permit(:department_id, :name, :kind)
    end
end

app/helpers/degree_plans_helper.rb
module DegreePlansHelper
end

app/views/degree_plans/_form.html.erb
<%= form_for(@degree_plan) do |f| %>
  <% if @degree_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree_plan.errors.count, "error") %> prohibited this degree_plan from being saved:</h2>

      <ul>
      <% @degree_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.text_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degree_plans/csv.csv.erb
<%= @csv %>

app/views/degree_plans/edit.html.erb
<h1>Editing Degree Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree_plan %> |
<%= link_to 'Back', degree_plans_path %>

app/views/degree_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Degree Plans</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Department</th>
      <th>Name</th>
      <th>Degree Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degree_plans.each do |degree_plan| %>
      <tr>
        <td><%= degree_plan.department.name %></td>
        <td><%= degree_plan.name %></td>
        <td><%= degree_plan.kind %></td>
        <td><%= link_to 'Edit Plan', degree_plan %></td>
        <td><%= link_to 'Change Name', edit_degree_plan_path(degree_plan) %></td>
        <td><%= link_to 'Destroy', degree_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree plan', new_degree_plan_path, class: 'btn btn-primary' %>

app/views/degree_plans/new.html.erb
<h1>New Degree Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', degree_plans_path %>

app/views/degree_plans/show.html.erb
<script>
/*global $, window*/
$.fn.editableTableWidget = function (options) {
  'use strict';
  return $(this).each(function () {
    var buildDefaultOptions = function () {
      var opts = $.extend({}, $.fn.editableTableWidget.defaultOptions);
      opts.editor = opts.editor.clone();
      return opts;
    },
    activeOptions = $.extend(buildDefaultOptions(), options),
    ARROW_LEFT = 37, ARROW_UP = 38, ARROW_RIGHT = 39, ARROW_DOWN = 40, ENTER = 13, ESC = 27, TAB = 9,
    element = $(this),
    editor = activeOptions.editor.css('position', 'absolute').hide().appendTo(element.parent()),
    active,
    showEditor = function (select) {
      active = element.find('td:focus');
      if (active.length) {
        editor.val(active.text())
        .removeClass('error')
        .show()
        .offset(active.offset())
        .css(active.css(activeOptions.cloneProperties))
        .width(active.width())
        .height(active.height())
        .focus();
        if (select) {
          editor.select();
        }
      }
    },
    setActiveText = function () {
      var text = editor.val(),
      evt = $.Event('change'),
      originalContent;
      if (active.text() === text || editor.hasClass('error')) {
        return true;
      }
      originalContent = active.html();
      active.text(text).trigger(evt, text);
      if (evt.result === false) {
        active.html(originalContent);
      }
    },
    movement = function (element, keycode) {
      if (keycode === ARROW_RIGHT) {
        return element.next('td');
      } else if (keycode === ARROW_LEFT) {
        return element.prev('td');
      } else if (keycode === ARROW_UP) {
        return element.parent().prev().children().eq(element.index());
      } else if (keycode === ARROW_DOWN) {
        return element.parent().next().children().eq(element.index());
      }
      return [];
    };
    editor.blur(function () {
        setActiveText();
        editor.hide();
    }).keydown(function (e) {
      if (e.which === ENTER) {
        setActiveText();
        editor.hide();
        active.focus();
        e.preventDefault();
        e.stopPropagation();
      } else if (e.which === ESC) {
        editor.val(active.text());
        e.preventDefault();
        e.stopPropagation();
        editor.hide();
        active.focus();
      } else if (e.which === TAB) {
        active.focus();
      } else if (this.selectionEnd - this.selectionStart === this.value.length) {
        var possibleMove = movement(active, e.which);
        if (possibleMove.length > 0) {
          possibleMove.focus();
          e.preventDefault();
          e.stopPropagation();
        }
      }
    })
    .on('input paste', function () {
      var evt = $.Event('validate');
      active.trigger(evt, editor.val());
      if (evt.result === false) {
        editor.addClass('error');
      } else {
        editor.removeClass('error');
      }
    });
    element.on('click keypress dblclick', showEditor)
    .css('cursor', 'pointer')
    .keydown(function (e) {
      var prevent = true,
      possibleMove = movement($(e.target), e.which);
      if (possibleMove.length > 0) {
        possibleMove.focus();
      } else if (e.which === ENTER) {
        showEditor(false);
      } else if (e.which === 17 || e.which === 91 || e.which === 93) {
        showEditor(true);
        prevent = false;
      } else {
        prevent = false;
      }
      if (prevent) {
        e.stopPropagation();
        e.preventDefault();
      }
    });

    element.find('td').prop('tabindex', 1);

    $(window).on('resize', function () {
      if (editor.is(':visible')) {
        editor.offset(active.offset())
        .width(active.width())
        .height(active.height());
      }
    });
  });

};
$.fn.editableTableWidget.defaultOptions = {
  cloneProperties: ['padding', 'padding-top', 'padding-bottom', 'padding-left', 'padding-right',
                    'text-align', 'font', 'font-size', 'font-family', 'font-weight',
                    'border', 'border-top', 'border-bottom', 'border-left', 'border-right'],
  editor: $('<input>')
};
</script>
<script>
function add_term_item(term_id) {
  $.ajax({
    url: "<%= term_items_path %>",
    data: { term_item: { term_id: term_id } },
    method: "POST"
  });
}
</script>

<p>
  <strong>Department:</strong>
  <%= @degree_plan.department.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @degree_plan.name %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @degree_plan.kind %>
</p>

<table class="table table-striped" id="all_terms">
  <tbody>
  <% @degree_plan.terms.each do |term| %>
    <%= render 'terms/term', term: term %>
  <% end %>
  </tbody>
</table>

<%= bootstrap_form_for Term.new, remote: true do |f| %>
  <%= f.hidden_field :degree_plan_id, value: @degree_plan.id %>
  <%= f.primary 'Add another Term' %>
<% end %>

<%= link_to 'Edit', edit_degree_plan_path(@degree_plan) %> |
<%= link_to 'Back', degree_plans_path %> |
<%= link_to 'Download CSV', csv_degree_plan_path(@degree_plan, :csv) %>
<script>
$('table').editableTableWidget();
$('table td').on('change', function(evt, newValue) {
  var term_item_id = evt.currentTarget.parentElement.getAttribute('data-term-item');
  var attribute = evt.currentTarget.getAttribute('data-attribute');
  ajax_data = {};
  ajax_data[attribute] = newValue;
  $.ajax({
    type: "PUT",
    dataType: "js",
    url: "<%= term_items_path %>" + "/" + term_item_id + ".js",
    data: { term_item: ajax_data }
  });
});
</script>