config/routes.rb
Rails.application.routes.draw do
  root 'degree_plans#index'

  resources :courses
  resources :term_items
  resources :course_term_items
  resources :term_item_terms
  resources :terms
  resources :users
  resources :degree_plans do
    member do
      get 'csv'
    end
  end
  resources :departments
  resources :colleges
  resources :years

end

app/models/term_item.rb
class TermItem < ActiveRecord::Base
  belongs_to :term
  has_many :course_term_items
  has_many :courses, through: :course_term_items
end

app/controllers/term_items_controller.rb
class TermItemsController < ApplicationController
  before_action :set_term_item, only: [:show, :edit, :update, :destroy]

  # GET /term_items
  # GET /term_items.json
  def index
    @term_items = TermItem.all
  end

  # GET /term_items/1
  # GET /term_items/1.json
  def show
  end

  # GET /term_items/new
  def new
    @term_item = TermItem.new
  end

  # GET /term_items/1/edit
  def edit
  end

  # POST /term_items
  # POST /term_items.json
  def create
    @term_item = TermItem.new(term_item_params)

    respond_to do |format|
      if @term_item.save
        format.html { redirect_to @term_item, notice: 'Term item was successfully created.' }
        format.json { render :show, status: :created, location: @term_item }
        format.js
      else
        format.html { render :new }
        format.json { render json: @term_item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /term_items/1
  # PATCH/PUT /term_items/1.json
  def update
    respond_to do |format|
      if @term_item.update(term_item_params)
        format.html { redirect_to @term_item, notice: 'Term item was successfully updated.' }
        format.json { render :show, status: :ok, location: @term_item }
        format.js { render nothing: true }
      else
        format.html { render :edit }
        format.json { render json: @term_item.errors, status: :unprocessable_entity }
        format.js { render nothing: true }
      end
    end
  end

  # DELETE /term_items/1
  # DELETE /term_items/1.json
  def destroy
    @term_item.destroy
    respond_to do |format|
      format.html { redirect_to term_items_url, notice: 'Term item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term_item
      @term_item = TermItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_item_params
      params.require(:term_item).permit(:term_id, :description, :hours, :minimum_grade, :notes)
    end
end

app/helpers/term_items_helper.rb
module TermItemsHelper
end

app/views/term_items/_form.html.erb
<%= form_for(@term_item) do |f| %>
  <% if @term_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term_item.errors.count, "error") %> prohibited this term_item from being saved:</h2>

      <ul>
      <% @term_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term_id %><br>
    <%= f.text_field :term_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :minimum_grade %><br>
    <%= f.text_field :minimum_grade %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/term_items/_term_item.html.erb
<tr data-term-item="<%= term_item.id %>">
  <td data-attribute="description"><%= term_item.description %></td>
  <td data-attribute="hours"><%= term_item.hours %></td>
  <td data-attribute="minimum_grade"><%= term_item.minimum_grade %></td>
  <td data-attribute="notes"><%= term_item.notes %></td>
</tr>

app/views/term_items/create.js.erb
$('#term_<%= @term_item.term_id %>').before('<%= j render 'term_items/term_item', term_item: @term_item %>');
$('table').editableTableWidget();
$('table td').on('change', function(evt, newValue) {
  var term_item_id = evt.currentTarget.parentElement.getAttribute('data-term-item');
  var attribute = evt.currentTarget.getAttribute('data-attribute');
  ajax_data = {};
  ajax_data[attribute] = newValue;
  $.ajax({
    type: "PUT",
    dataType: "js",
    url: "<%= term_items_path %>" + "/" + term_item_id + ".js",
    data: { term_item: ajax_data }
  });
});

app/views/term_items/edit.html.erb
<h1>Editing Term Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @term_item %> |
<%= link_to 'Back', term_items_path %>

app/views/term_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Term Items</h1>

<table>
  <thead>
    <tr>
      <th>Term</th>
      <th>Description</th>
      <th>Hours</th>
      <th>Minimum grade</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @term_items.each do |term_item| %>
      <tr>
        <td><%= term_item.term %></td>
        <td><%= term_item.description %></td>
        <td><%= term_item.hours %></td>
        <td><%= term_item.minimum_grade %></td>
        <td><%= term_item.notes %></td>
        <td><%= link_to 'Show', term_item %></td>
        <td><%= link_to 'Edit', edit_term_item_path(term_item) %></td>
        <td><%= link_to 'Destroy', term_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term item', new_term_item_path %>

app/views/term_items/new.html.erb
<h1>New Term Item</h1>

<%= render 'form' %>

<%= link_to 'Back', term_items_path %>

app/views/term_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @term_item.term %>
</p>

<p>
  <strong>Description:</strong>
  <%= @term_item.description %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @term_item.hours %>
</p>

<p>
  <strong>Minimum grade:</strong>
  <%= @term_item.minimum_grade %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @term_item.notes %>
</p>

<%= link_to 'Edit', edit_term_item_path(@term_item) %> |
<%= link_to 'Back', term_items_path %>